
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "home", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:4343/home?wsdl")
public class Home
    extends Service
{

    private final static URL HOME_WSDL_LOCATION;
    private final static WebServiceException HOME_EXCEPTION;
    private final static QName HOME_QNAME = new QName("http://webservices/", "home");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:4343/home?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOME_WSDL_LOCATION = url;
        HOME_EXCEPTION = e;
    }

    public Home() {
        super(__getWsdlLocation(), HOME_QNAME);
    }

    public Home(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOME_QNAME, features);
    }

    public Home(URL wsdlLocation) {
        super(wsdlLocation, HOME_QNAME);
    }

    public Home(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOME_QNAME, features);
    }

    public Home(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Home(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HomeServices
     */
    @WebEndpoint(name = "HomeServicesPort")
    public HomeServices getHomeServicesPort() {
        return super.getPort(new QName("http://webservices/", "HomeServicesPort"), HomeServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HomeServices
     */
    @WebEndpoint(name = "HomeServicesPort")
    public HomeServices getHomeServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "HomeServicesPort"), HomeServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOME_EXCEPTION!= null) {
            throw HOME_EXCEPTION;
        }
        return HOME_WSDL_LOCATION;
    }

}
